packages:
  - apps/*
  - config/*
  - packages/*

catalog:
  '@tailwindcss/postcss': ^4.1.18
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^25.0.8
  '@types/react': ^19.2.8
  'react': ^19.2.3
  'react-dom': ^19.2.3
  'tailwindcss': ^4.1.18
  'typescript': ^5.9.3
  'vite-tsconfig-paths': ^6.0.4
  'vitest': ^4.0.17
