packages:
  - apps/*
  - config/*
  - packages/*

catalog:
  '@tailwindcss/postcss': 4.3.0
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.2
  '@testing-library/user-event': 14.6.1
  '@types/node': 24.1.0
  '@types/react': 19.2.18
  '@vitejs/plugin-react': 6.0.2
  'clsx': 2.1.1
  'react': 19.2.8
  'react-dom': 19.2.8
  'tailwindcss': 4.3.0
  'typescript': 7.0.2
  'vitest': 4.1.8
