packages:
  - apps/*
  - config/*
  - packages/*

catalog:
  '@types/node': ^25.0.8
  '@types/react': ^19.2.8
  'react': ^19.2.3
  'react-dom': ^19.2.3
  'typescript': ^5.9.3
  'vite-tsconfig-paths': ^6.0.4
  'vitest': ^4.0.17
